# Site settings
title: "TextLog"
description: "Minimalist Jekyll theme for documentation site"
baseurl:  # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://japaniot.github.io"
author: "John Doe"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
